
all:
	$(MAKE) -C conv
	$(MAKE) -C decoup
	$(MAKE) -C split
	$(MAKE) -C narrow
	$(MAKE) -C nonlin

clean:
	$(MAKE) -C conv clean
	$(MAKE) -C decoup clean
	$(MAKE) -C split clean
	$(MAKE) -C narrow clean
	$(MAKE) -C nonlin clean

again: clean all

